# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

markdown: kramdown

# Setup
title:               UfoRoblog
tagline:             'A blog about stuff'
description:         ''
url:                 uforobot.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Ascanio Vimercati Sanseverino
  url:               
  email:             ascanio.vimercati@gmail.com
  
# Custom vars
#version:             1.0.0

theme: jekyll-theme-minimal
